name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      IVERILOG_VERSION: v11_0
      YOSYS_VERSION: yosys-0.23
      GHDL_VERSION: v2.0.0
      GHDL_YOSYS_PLUGIN_VERSION: c9b05e48

    steps:
      - name: Setup repository
        if: ${{ !env.ACT }}
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y git
          pip3 install -r requirements.txt

      - name: Install iverilog
        run: |
          sudo apt install -y git build-essential python3 python3-pip \
            autotools-dev autoconf gperf flex bison

          git clone https://github.com/steveicarus/iverilog iverilog
          pushd iverilog
            git checkout ${IVERILOG_VERSION}
            chmod u+rwx ./autoconf.sh
            ./autoconf.sh
            ./configure
            make -j$(nproc)
            sudo make install
          popd

      - name: Install Yosys
        run: |
          sudo apt install -y build-essential clang bison flex \
            libreadline-dev gawk tcl-dev libffi-dev git \
            graphviz xdot pkg-config python3 libboost-system-dev \
            libboost-python-dev libboost-filesystem-dev zlib1g-dev

          git clone --recursive https://github.com/YosysHQ/yosys yosys
          pushd yosys
            git checkout ${YOSYS_VERSION}
            make -j$(nproc) config-gcc
            sudo make -j$(nproc) install
          popd

      - name: Install GHDL
        run: |
          sudo apt install -y gnat
          git clone --recursive https://github.com/ghdl/ghdl ghdl
          pushd ghdl
            git checkout ${GHDL_VERSION}
            ./configure
            make -j$(nproc)
            sudo make -j$(nproc) install
          popd

      - name: Install GHDL Yosys plugin
        run: |
          git clone https://github.com/ghdl/ghdl-yosys-plugin
          pushd ghdl-yosys-plugin
            git checkout ${GHDL_YOSYS_PLUGIN_VERSION}
            make -j$(nproc)
            sudo make -j$(nproc) install
          popd

      - name: Run tests
        run: |
          make generate-vhdl
          make test

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: |
            tests/build
