name: Tests
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        if: ${{ !env.ACT }}
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y git
          pip3 install -r requirements.txt

      - name: Install iverilog
        run: |
          sudo apt install -y git build-essential python3 python3-pip \
            autotools-dev autoconf gperf flex bison

          git clone https://github.com/steveicarus/iverilog iverilog
          pushd iverilog
            chmod u+rwx ./autoconf.sh
            ./autoconf.sh
            ./configure
            make -j$(nproc)
            sudo make install
          popd

      - name: Install Yosys
        run: |
          sudo apt install -y build-essential clang bison flex \
            libreadline-dev gawk tcl-dev libffi-dev git \
            graphviz xdot pkg-config python3 libboost-system-dev \
            libboost-python-dev libboost-filesystem-dev zlib1g-dev

          git clone --recursive https://github.com/YosysHQ/yosys yosys
          pushd yosys
            make -j$(nproc) config-gcc
            sudo make -j$(nproc) install
          popd

      - name: Install GHDL
        run: |
          sudo apt install -y gnat
          git clone --recursive https://github.com/ghdl/ghdl ghdl
          pushd ghdl
            ./configure
            make -j$(nproc)
            sudo make -j$(nproc) install
          popd

      - name: Install GHDL Yosys plugin
        run: |
          git clone https://github.com/ghdl/ghdl-yosys-plugin
          pushd ghdl-yosys-plugin
            make -j$(nproc)
            sudo make -j$(nproc) install
          popd

      - name: Run tests
        run: |
          make generate-vhdl
          make test

      - name: Upload artifacts
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: |
            tests/build
